# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'try_gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(465, 500)
        self.xianshi2 = QtWidgets.QTextEdit(Form)
        self.xianshi2.setGeometry(QtCore.QRect(30, 100, 261, 361))
        self.xianshi2.setLineWrapMode(QtWidgets.QTextEdit.WidgetWidth)
        self.xianshi2.setReadOnly(True)
        self.xianshi2.setObjectName("xianshi2")
        self.pb_gaojing = QtWidgets.QPushButton(Form)
        self.pb_gaojing.setGeometry(QtCore.QRect(334, 317, 91, 23))
        self.pb_gaojing.setObjectName("pb_gaojing")
        self.pb_shebeiID = QtWidgets.QPushButton(Form)
        self.pb_shebeiID.setEnabled(True)
        self.pb_shebeiID.setGeometry(QtCore.QRect(334, 346, 91, 23))
        self.pb_shebeiID.setSizeIncrement(QtCore.QSize(0, 0))
        self.pb_shebeiID.setObjectName("pb_shebeiID")
        self.pb_shujuleixing = QtWidgets.QPushButton(Form)
        self.pb_shujuleixing.setGeometry(QtCore.QRect(334, 375, 91, 23))
        self.pb_shujuleixing.setObjectName("pb_shujuleixing")
        self.label_daoru = QtWidgets.QLabel(Form)
        self.label_daoru.setGeometry(QtCore.QRect(10, 18, 54, 12))
        self.label_daoru.setObjectName("label_daoru")
        self.label_zhuangtai = QtWidgets.QLabel(Form)
        self.label_zhuangtai.setGeometry(QtCore.QRect(10, 80, 61, 16))
        self.label_zhuangtai.setObjectName("label_zhuangtai")
        self.label_gongneng = QtWidgets.QLabel(Form)
        self.label_gongneng.setGeometry(QtCore.QRect(322, 125, 54, 12))
        self.label_gongneng.setObjectName("label_gongneng")
        self.pb_kongge = QtWidgets.QPushButton(Form)
        self.pb_kongge.setEnabled(False)
        self.pb_kongge.setGeometry(QtCore.QRect(335, 408, 91, 23))
        self.pb_kongge.setObjectName("pb_kongge")
        self.pushButton_2 = QtWidgets.QPushButton(Form)
        self.pushButton_2.setEnabled(False)
        self.pushButton_2.setGeometry(QtCore.QRect(335, 438, 91, 23))
        self.pushButton_2.setObjectName("pushButton_2")
        self.layoutWidget = QtWidgets.QWidget(Form)
        self.layoutWidget.setGeometry(QtCore.QRect(31, 39, 421, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.xianshi1 = QtWidgets.QLineEdit(self.layoutWidget)
        self.xianshi1.setReadOnly(True)
        self.xianshi1.setObjectName("xianshi1")
        self.horizontalLayout.addWidget(self.xianshi1)
        self.pb_daorutxt = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_daorutxt.setObjectName("pb_daorutxt")
        self.horizontalLayout.addWidget(self.pb_daorutxt)
        self.pb_shuchutxt = QtWidgets.QPushButton(self.layoutWidget)
        self.pb_shuchutxt.setObjectName("pb_shuchutxt")
        self.horizontalLayout.addWidget(self.pb_shuchutxt)
        self.label_gongneng_2 = QtWidgets.QLabel(Form)
        self.label_gongneng_2.setGeometry(QtCore.QRect(324, 75, 101, 16))
        self.label_gongneng_2.setObjectName("label_gongneng_2")
        self.lineEdit_zhanmingsuoxie = QtWidgets.QLineEdit(Form)
        self.lineEdit_zhanmingsuoxie.setGeometry(QtCore.QRect(334, 95, 91, 20))
        self.lineEdit_zhanmingsuoxie.setObjectName("lineEdit_zhanmingsuoxie")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(310, 470, 151, 20))
        self.label.setObjectName("label")
        self.pb_kongzhiwei = QtWidgets.QPushButton(Form)
        self.pb_kongzhiwei.setGeometry(QtCore.QRect(333, 146, 91, 23))
        self.pb_kongzhiwei.setObjectName("pb_kongzhiwei")
        self.pb_dianhao = QtWidgets.QPushButton(Form)
        self.pb_dianhao.setGeometry(QtCore.QRect(333, 175, 91, 23))
        self.pb_dianhao.setObjectName("pb_dianhao")
        self.pb_xinghaoleixing = QtWidgets.QPushButton(Form)
        self.pb_xinghaoleixing.setGeometry(QtCore.QRect(333, 216, 91, 23))
        self.pb_xinghaoleixing.setObjectName("pb_xinghaoleixing")
        self.pb_guangzi = QtWidgets.QPushButton(Form)
        self.pb_guangzi.setGeometry(QtCore.QRect(333, 245, 91, 23))
        self.pb_guangzi.setObjectName("pb_guangzi")
        self.pb_qufan = QtWidgets.QPushButton(Form)
        self.pb_qufan.setGeometry(QtCore.QRect(333, 274, 91, 23))
        self.pb_qufan.setObjectName("pb_qufan")

        self.retranslateUi(Form)
        self.pb_daorutxt.clicked.connect(Form.pb_daorutxt1)
        self.pb_xinghaoleixing.clicked.connect(Form.pb_xinghaoleixing1)
        self.pb_shuchutxt.clicked.connect(Form.pb_shuchutxt1)
        self.pb_kongzhiwei.clicked.connect(Form.pb_kongzhiwei1)
        self.pb_dianhao.clicked.connect(Form.pb_dianhao1)
        self.pb_guangzi.clicked.connect(Form.pb_guangzipai1)
        self.pb_qufan.clicked.connect(Form.pb_qufan1)
        self.pb_gaojing.clicked.connect(Form.pb_gaojing1)
        self.pb_shebeiID.clicked.connect(Form.pb_shebeiID1)
        self.pb_shujuleixing.clicked.connect(Form.pb_xinghaoleixing1)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "保护信息数据支撑系统V3.3"))
        self.pb_gaojing.setText(_translate("Form", "生成告警级别"))
        self.pb_shebeiID.setText(_translate("Form", "生成设备ID"))
        self.pb_shujuleixing.setText(_translate("Form", "生成数据类型"))
        self.label_daoru.setText(_translate("Form", "导入模块"))
        self.label_zhuangtai.setText(_translate("Form", "状态显示栏"))
        self.label_gongneng.setText(_translate("Form", "功能模块"))
        self.pb_kongge.setText(_translate("Form", "替换空格"))
        self.pushButton_2.setText(_translate("Form", "替换双引号"))
        self.pb_daorutxt.setText(_translate("Form", "导入TXT"))
        self.pb_shuchutxt.setText(_translate("Form", "输出TXT"))
        self.label_gongneng_2.setText(_translate("Form", "输入站名缩写："))
        self.label.setText(_translate("Form", "呼和浩特供电局调度管理处"))
        self.pb_kongzhiwei.setText(_translate("Form", "控制位=0"))
        self.pb_dianhao.setText(_translate("Form", "初始化点号"))
        self.pb_xinghaoleixing.setText(_translate("Form", "信号类型=1"))
        self.pb_guangzi.setText(_translate("Form", "光字牌=1"))
        self.pb_qufan.setText(_translate("Form", "取反=0"))
